/**
 * Applies pending migrations, forward only, on launch.
 *
 * Migrations are plain .sql generated by drizzle-kit and committed. They are
 * applied by hand rather than through Drizzle's migrator so that the journal
 * table, the ordering and the failure behaviour are all visible here, and so
 * that a packaged app does not depend on Drizzle's folder layout surviving the
 * build.
 *
 * Never edit a migration that has been applied on a real machine. Add a new one.
 * See .claude/rules/data.md.
 */
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { ShimDatabase } from "./node-sqlite-shim";

export interface MigrationResult {
	applied: string[];
	alreadyCurrent: number;
}

/**
 * In development the compiled main process runs from dist-electron/, and the
 * build copies the migrations next to it. Both cases resolve the same way.
 */
export function migrationsDir(): string {
	return join(__dirname, "migrations");
}

export function runMigrations(
	connection: ShimDatabase,
	dir = migrationsDir(),
): MigrationResult {
	connection.exec(`
		CREATE TABLE IF NOT EXISTS _migrations (
			name TEXT PRIMARY KEY,
			applied_at TEXT NOT NULL
		)
	`);

	const done = new Set(
		(connection.prepare("SELECT name FROM _migrations").all() as { name: string }[]).map(
			(r) => r.name,
		),
	);

	// Lexical order is the apply order, which is why drizzle-kit's numeric prefix
	// matters. A merge that produces two files with the same prefix is a conflict
	// to resolve by regenerating, not by renaming.
	const files = readdirSync(dir)
		.filter((f) => f.endsWith(".sql"))
		.sort();

	const applied: string[] = [];

	for (const file of files) {
		if (done.has(file)) continue;
		const sql = readFileSync(join(dir, file), "utf8");

		// drizzle-kit separates statements with this marker. Splitting on semicolons
		// would break any statement containing one inside a string literal.
		const statements = sql
			.split("--> statement-breakpoint")
			.map((s) => s.trim())
			.filter(Boolean);

		// Foreign keys go off for the duration, which is SQLite's own recipe for a
		// schema change and not a shortcut.
		//
		// A table that cannot be altered in place is rebuilt: new table, copy,
		// drop the old one, rename. `DROP TABLE` performs an implicit delete of
		// every parent row, so with enforcement on it fails the moment any child
		// row points at the table being rebuilt, and `defer_foreign_keys` does not
		// save it: the deferred counter is raised by the drop and nothing lowers it
		// again when the rows come back under a renamed table. The pragma is also a
		// no-op inside a transaction, which is why it is set out here.
		//
		// What replaces the enforcement is the check below, inside the same
		// transaction: a migration that leaves a dangling reference throws and
		// rolls back. That is stricter than running with keys on, because it looks
		// at the whole database rather than only at the rows a statement touched.
		connection.exec("PRAGMA foreign_keys = OFF");
		try {
			// One transaction per migration file: a half-applied migration is the
			// worst possible state, because the journal would disagree with the
			// schema.
			connection.transaction(() => {
				for (const statement of statements) connection.exec(statement);

				const broken = connection.prepare("PRAGMA foreign_key_check").all();
				if (broken.length > 0) {
					throw new Error(
						`${file} left ${broken.length} rows pointing at something that is not there. Nothing was applied.`,
					);
				}

				connection
					.prepare("INSERT INTO _migrations (name, applied_at) VALUES (?, ?)")
					.run(file, new Date().toISOString());
			})();
		} finally {
			connection.exec("PRAGMA foreign_keys = ON");
		}

		applied.push(file);
	}

	return { applied, alreadyCurrent: files.length - applied.length };
}
